[package]
name = "Ray-Rengine"
version = "0.1.0"
authors = ["ameerwasi001 <54429413+ameerwasi001@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
